"""
Django settings for shoping project.

Generated by 'django-admin startproject' using Django 5.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""
import os.path
from pathlib import Path

from django.conf import locale
from django.utils.translation import gettext_lazy as _

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-t9unfg@lqtc$grasju#r)$zcpwah28zfgpmtn75-si6^jr9w*b"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []

# Application definition

INSTALLED_APPS = [
    'simpleui',
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    'apps.user',
    'channels',
    'apps.service',

]
SIMPLEUI = {
    'show_theme_change': False,  # 核心配置：隐藏主题按钮
}
MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'apps.user.utils.auth_middle.AuthLogin',
]

ROOT_URLCONF = "shoping.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [os.path.join(BASE_DIR, 'templates')]
        ,
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                'apps.user.views.cart_count',
                'django.template.context_processors.media',

            ],
        },
    },
]

WSGI_APPLICATION = "shoping.wsgi.application"

# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.mysql",
        "NAME": "mydb",
        'USER': 'root',
        'PASSWORD': '123456',
        'HOST': 'localhost',
        'PORT': '3306'
    }
}

# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]

# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

# LANGUAGE_CODE = "en-us"
LANGUAGE_CODE = 'zh-hans'
TIME_ZONE = 'Asia/Shanghai'

# TIME_ZONE = "UTC"

USE_I18N = True
USE_TZ = False

LOGIN_URL = 'login'
LOGOUT_REDIRECT_URL = '/admin/login/'

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = "static/"
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
]
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

SIMPLEUI_LOGO = '/static/images/logo.png'  # 设置顶部导航栏Logo
SIMPLEUI_LOGIN_LOGO = '/static/images/logo.png'
SIMPLEUI_HOME_PAGE = 'http://127.0.0.1:8000/static/images/zc.png'
SIMPLEUI_LOGIN_PARTICLES = False
DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

SIMPLEUI_CONFIG = {
    'system_keep': False,
    'show_theme_change': False,
    'menu_display': ['首饰管理','订单管理', '首饰类型', '用户浏览报表查看', '评论管理', '用户消息管理', '投诉管理', '用户管理',],
    'dynamic': True,
    'homepage': None,
    'menus': [
        {'name': '首饰管理', 'icon': 'el-icon-s-promotion', 'url': '/admin/user/goods/'},
        {'name': '订单管理', 'icon': 'el-icon-goods', 'url': '/admin/user/order/'},
        {'name': '首饰类型', 'icon': 'el-icon-loading', 'url': '/admin/user/goodstype/'},
        {'name': '用户浏览报表查看', 'icon': 'el-icon-coordinate', 'url': '/admin/user/browse/'},
        {'name': '评论管理', 'icon': 'fa-solid fa-envelope', 'url': '/admin/user/evaluate/'},
        {'name': '用户消息管理', 'icon': 'el-icon-goods', 'url': '/admin/service/'},
        {'name': '投诉管理', 'icon': 'fa-solid fa-envelope', 'url': '/admin/user/feedback_user/'},
        {'name': '用户管理', 'icon': 'el-icon-user-solid', 'url': '/admin/auth/user/'},

    ]
}


SIMPLEUI_HOME_INFO = False
SIMPLEUI_STATIC_OFFLINE = True
MESSAGE_STORAGE = 'django.contrib.messages.storage.session.SessionStorage'

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
# 设置媒体文件的存储位置
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# 设置媒体文件的URL
MEDIA_URL = '/media/'
ASGI_APPLICATION = 'shoping.asgi.application'

CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels.layers.InMemoryChannelLayer"
    }
}