# Generated by Django 5.0.6 on 2025-08-19 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Face',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='名字')),
                ('image', models.CharField(max_length=255, verbose_name='文件名')),
            ],
            options={
                'verbose_name': '表情包',
                'db_table': 'face',
            },
        ),
    ]
