# Generated by Django 5.0.6 on 2025-08-19 18:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=255, verbose_name='用户')),
                ('sku_id', models.IntegerField(verbose_name='商品ID')),
                ('count', models.IntegerField(verbose_name='数量')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '购物车信息',
                'db_table': 'cart',
            },
        ),
        migrations.CreateModel(
            name='FeedBack_user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=255, verbose_name='用户')),
                ('textarea_name', models.TextField(verbose_name='反馈内容')),
                ('input_name', models.CharField(max_length=255, verbose_name='手机号码')),
                ('feedback_number', models.CharField(max_length=255, unique=True, verbose_name='反馈ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='反馈时间')),
            ],
            options={
                'verbose_name': '用户反馈',
                'db_table': 'feedback_user',
            },
        ),
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goods_name', models.CharField(max_length=255, verbose_name='商品名称')),
                ('intro', models.CharField(max_length=255, verbose_name='简介')),
                ('sell', models.IntegerField(verbose_name='售出')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='价格')),
                ('cation', models.CharField(max_length=255, verbose_name='计量')),
                ('images', models.CharField(max_length=255, verbose_name='图片路径')),
            ],
            options={
                'verbose_name': '商品信息',
                'db_table': 'goods',
            },
        ),
        migrations.CreateModel(
            name='GoodsType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goods_type_name', models.CharField(max_length=255, verbose_name='商品类型名称')),
                ('images', models.CharField(max_length=255, verbose_name='类型图片路径')),
                ('class_name', models.CharField(max_length=255, verbose_name='所属的类属性')),
            ],
            options={
                'verbose_name': '商品类型',
                'db_table': 'goods_type',
            },
        ),
        migrations.CreateModel(
            name='FeedBack_Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='uploads/')),
                ('feedback_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.feedback_user', to_field='feedback_number', verbose_name='反馈ID')),
            ],
            options={
                'db_table': 'feedback_image',
            },
        ),
        migrations.CreateModel(
            name='Evaluate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=255)),
                ('evaluate', models.CharField(max_length=1000, verbose_name='商品评论')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('sku_id', models.ForeignKey(db_column='sku_id', on_delete=django.db.models.deletion.CASCADE, to='user.goods', verbose_name='商品')),
            ],
            options={
                'verbose_name': '商品评论',
                'db_table': 'evaluate',
            },
        ),
        migrations.CreateModel(
            name='Browse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=255, verbose_name='用户')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('sku_id', models.ForeignKey(db_column='sku_id', on_delete=django.db.models.deletion.CASCADE, to='user.goods', verbose_name='商品')),
            ],
            options={
                'db_table': 'browse',
            },
        ),
        migrations.AddField(
            model_name='goods',
            name='type_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.goodstype', verbose_name='商城所属类型'),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=255, verbose_name='用户')),
                ('order_number', models.CharField(max_length=255, verbose_name='订单号')),
                ('count', models.IntegerField(verbose_name='商品数量')),
                ('status', models.CharField(max_length=20, verbose_name='订单状态')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('evaluate', models.IntegerField(choices=[(0, '未评价'), (1, '已评价')], default=0, verbose_name='是否评价')),
                ('sku_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.goods', verbose_name='商品')),
            ],
            options={
                'db_table': 'order',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'service',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(0, '发送'), (1, '接收')])),
                ('service', models.CharField(default='hello', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('reading', models.IntegerField(choices=[(0, '未读'), (1, '已读')], default=0)),
                ('type', models.CharField(default='text', max_length=255, verbose_name='消息类型')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.service')),
            ],
            options={
                'db_table': 'message',
            },
        ),
    ]
